"""Persistence for action proposals.

Stores proposed actions generated by ActionProposer. Each row is one proposal
tied to a cycle_id with its gate_level, status, source_refs and payload.
Status lifecycle: proposed -> approved|rejected|skipped -> executed (when
approved and the runner picks it up).

Schema is idempotent (`CREATE TABLE IF NOT EXISTS`). No destructive ALTERs.
"""
from __future__ import annotations

import json
import logging
import re
from datetime import datetime
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)

SOURCE_REF_RE = re.compile(
    r"^(?:loop|conversation|dream|will|meta|rumination_insight|"
    r"relational_state|working_memory|knowledge_gap|goal_\w+|"
    r"work_\w+|hobby_artifact|agent_development|action_proposal)#\d+$"
)

VALID_STATUSES = ("proposed", "approved", "rejected", "skipped", "executed", "failed")
VALID_GATES = (
    "internal_only",
    "admin_communicate",
    "artifact_for_review",
    "external_publish",
)


def _json_dumps(value: Any) -> str:
    if value is None:
        return "[]"
    try:
        return json.dumps(value, ensure_ascii=False, default=str)
    except Exception:
        return "[]"


def _json_loads(value: Any, default: Any) -> Any:
    if value is None:
        return default
    if isinstance(value, (dict, list)):
        return value
    try:
        return json.loads(value)
    except Exception:
        return default


def _normalize_source_refs(refs: Any, *, required: bool = False) -> List[str]:
    if refs is None:
        refs_list: List[str] = []
    elif isinstance(refs, str):
        refs_list = [refs]
    else:
        refs_list = list(refs)
    clean: List[str] = []
    for ref in refs_list:
        ref_str = str(ref).strip()
        if not ref_str:
            continue
        if not SOURCE_REF_RE.fullmatch(ref_str):
            raise ValueError(f"invalid_source_ref:{ref_str}")
        clean.append(ref_str)
    if required and not clean:
        raise ValueError("source_refs_required")
    return clean


def _normalize_status(status: Any) -> str:
    if status is None:
        return "proposed"
    s = str(status).strip().lower()
    if s not in VALID_STATUSES:
        raise ValueError(f"invalid_status:{status}")
    return s


def _normalize_gate(gate: Any) -> str:
    if gate is None:
        raise ValueError("gate_level_required")
    g = str(gate).strip().lower()
    if g not in VALID_GATES:
        raise ValueError(f"invalid_gate_level:{gate}")
    return g


class ActionProposalDatabaseMixin:
    """Mixin offering action_proposals persistence to HybridDatabaseManager."""

    def _init_action_proposals_schema(self) -> None:
        cursor = self.conn.cursor()
        cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS action_proposals (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                agent_instance TEXT NOT NULL,
                cycle_id TEXT NOT NULL,
                user_id TEXT NOT NULL,
                will_drive TEXT,
                action_type TEXT NOT NULL,
                gate_level TEXT NOT NULL,
                status TEXT NOT NULL DEFAULT 'proposed',
                confidence REAL,
                source_refs_json TEXT DEFAULT '[]',
                payload_json TEXT DEFAULT '{}',
                rationale TEXT,
                created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
                decided_at DATETIME,
                updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
            )
            """
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_action_proposals_cycle "
            "ON action_proposals(agent_instance, cycle_id, created_at DESC)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_action_proposals_status "
            "ON action_proposals(status, created_at DESC)"
        )
        cursor.execute(
            "CREATE INDEX IF NOT EXISTS idx_action_proposals_pending "
            "ON action_proposals(agent_instance, cycle_id, action_type, status)"
        )
        self.conn.commit()

    def create_action_proposal(
        self,
        *,
        agent_instance: str,
        cycle_id: str,
        user_id: str,
        will_drive: Optional[str] = None,
        action_type: str,
        gate_level: str,
        status: str = "proposed",
        confidence: Optional[float] = None,
        source_refs: Any = None,
        payload: Optional[Dict[str, Any]] = None,
        rationale: Optional[str] = None,
    ) -> int:
        gate = _normalize_gate(gate_level)
        normalized_status = _normalize_status(status)
        refs = _normalize_source_refs(source_refs, required=True)
        cursor = self.conn.cursor()
        with self._lock:
            cursor.execute(
                """
                INSERT INTO action_proposals (
                    agent_instance, cycle_id, user_id, will_drive,
                    action_type, gate_level, status, confidence,
                    source_refs_json, payload_json, rationale,
                    created_at, updated_at
                ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
                """,
                (
                    agent_instance,
                    cycle_id,
                    user_id,
                    will_drive,
                    action_type,
                    gate,
                    normalized_status,
                    confidence,
                    _json_dumps(refs),
                    _json_dumps(payload or {}),
                    rationale,
                    datetime.utcnow().isoformat(),
                    datetime.utcnow().isoformat(),
                ),
            )
            self.conn.commit()
            return int(cursor.lastrowid)

    def list_action_proposals(
        self,
        *,
        agent_instance: str,
        cycle_id: Optional[str] = None,
        status: Optional[str] = None,
        limit: int = 50,
    ) -> List[Dict[str, Any]]:
        clauses = ["agent_instance = ?"]
        params: List[Any] = [agent_instance]
        if cycle_id is not None:
            clauses.append("cycle_id = ?")
            params.append(cycle_id)
        if status is not None:
            clauses.append("status = ?")
            params.append(_normalize_status(status))
        cursor = self.conn.cursor()
        cursor.execute(
            f"""
            SELECT * FROM action_proposals
            WHERE {' AND '.join(clauses)}
            ORDER BY created_at DESC, id DESC
            LIMIT ?
            """,
            tuple(params) + (int(limit),),
        )
        return [self._action_proposal_row_to_dict(row) for row in cursor.fetchall()]

    def get_latest_action_proposal_for(
        self,
        *,
        agent_instance: str,
        action_type: str,
        status: Optional[str] = None,
    ) -> Optional[Dict[str, Any]]:
        clauses = ["agent_instance = ?", "action_type = ?"]
        params: List[Any] = [agent_instance, action_type]
        if status is not None:
            clauses.append("status = ?")
            params.append(_normalize_status(status))
        cursor = self.conn.cursor()
        cursor.execute(
            f"""
            SELECT * FROM action_proposals
            WHERE {' AND '.join(clauses)}
            ORDER BY created_at DESC, id DESC
            LIMIT 1
            """,
            tuple(params),
        )
        row = cursor.fetchone()
        return self._action_proposal_row_to_dict(row) if row else None

    def count_action_proposals_for_cycle(
        self,
        *,
        agent_instance: str,
        cycle_id: str,
        exclude_skipped: bool = True,
    ) -> int:
        clauses = ["agent_instance = ?", "cycle_id = ?"]
        params: List[Any] = [agent_instance, cycle_id]
        if exclude_skipped:
            clauses.append("status != 'skipped'")
        cursor = self.conn.cursor()
        cursor.execute(
            f"""
            SELECT COUNT(*) AS n FROM action_proposals
            WHERE {' AND '.join(clauses)}
            """,
            tuple(params),
        )
        row = cursor.fetchone()
        return int(row[0]) if row else 0

    def update_action_proposal_status(
        self,
        *,
        proposal_id: int,
        status: str,
        decided_at: Optional[Any] = None,
    ) -> bool:
        normalized_status = _normalize_status(status)
        decided_iso = (
            decided_at.isoformat()
            if isinstance(decided_at, datetime)
            else (decided_at or datetime.utcnow().isoformat())
        )
        cursor = self.conn.cursor()
        with self._lock:
            cursor.execute(
                """
                UPDATE action_proposals
                SET status = ?, decided_at = ?, updated_at = ?
                WHERE id = ?
                """,
                (normalized_status, decided_iso, datetime.utcnow().isoformat(), int(proposal_id)),
            )
            self.conn.commit()
            return cursor.rowcount > 0

    def _action_proposal_row_to_dict(self, row: Any) -> Dict[str, Any]:
        cols = (
            "id",
            "agent_instance",
            "cycle_id",
            "user_id",
            "will_drive",
            "action_type",
            "gate_level",
            "status",
            "confidence",
            "source_refs_json",
            "payload_json",
            "rationale",
            "created_at",
            "decided_at",
            "updated_at",
        )
        data = dict(zip(cols, row))
        data["source_refs"] = _json_loads(data.pop("source_refs_json", "[]"), default=[])
        data["payload"] = _json_loads(data.pop("payload_json", "{}"), default={})
        return data
